
substitutions:
  device_name: slimmelezer-p1
  device_description: "DIY P1 module to read your smart meter"
  ip: !secret slimmelezer_ip

esp8266:
  board: d1_mini
  restore_from_flash: True

esphome:
  name: ${device_name}
  comment: "${device_description}"
  name_add_mac_suffix: false
  project:
    name: zuidwijk.slimmelezer
    version: "1.0"
  # on_boot:
  #   then:
  #     - if:
  #         condition:
  #           lambda: return id(has_key);
  #         then:
  #           - lambda: |-
  #               std::string key(id(stored_decryption_key), 32);
  #               id(dsmr_instance).set_decryption_key(key);
  #         else:
  #           - logger.log:
  #               level: info
  #               format: "Not using decryption key. If you need to set a key use Home Assistant service 'ESPHome:  ${device_name}_set_dsmr_key'"

<<: !include .common.yaml

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  services:
    service: set_dsmr_key
    variables:
      private_key: string
    then:
      - logger.log:
          format: Setting private key %s. Set to empty string to disable
          args: [private_key.c_str()]
      # - globals.set:
      #     id: has_key
      #     value: !lambda "return private_key.length() == 32;"
      # - lambda: |-
      #     if (private_key.length() == 32)
      #       private_key.copy(id(stored_decryption_key), 32);
      #     id(dsmr_instance).set_decryption_key(private_key);

uart:
  baud_rate: 115200
  rx_pin: D7

globals:
  - id: has_key
    type: bool
    restore_value: yes
    initial_value: "false"
  - id: stored_decryption_key
    type: char[32]
    restore_value: yes

dsmr:
  id: dsmr_instance

sensor:
  - platform: dsmr
    energy_delivered_tariff1:
      name: "Energy Consumed Tariff 1"
      state_class: total_increasing
    energy_delivered_tariff2:
      name: "Energy Consumed Tariff 2"
      state_class: total_increasing
    energy_returned_tariff1:
      name: "Energy Produced Tariff 1"
      state_class: total_increasing
    energy_returned_tariff2:
      name: "Energy Produced Tariff 2"
      state_class: total_increasing
    power_delivered:
      name: "Power Consumed"
      accuracy_decimals: 3
      # Apply default filters on all sensors, this limits the number of state changes in HA
      filters:
        - throttle: 5s
        - delta: 1
    power_returned:
      name: "Power Produced"
      accuracy_decimals: 3
      filters:
        - throttle: 5s
        - delta: 1
    electricity_failures:
      name: "Electricity Failures"
      icon: mdi:alert
      filters:
        - throttle: 60s
    electricity_long_failures:
      name: "Long Electricity Failures"
      icon: mdi:alert
      filters:
        - throttle: 60s
    voltage_l1:
      name: "Voltage Phase 1"
      filters:
        - delta: 1
        - throttle: 60s
    voltage_l2:
      name: "Voltage Phase 2"
      filters:
        - delta: 1
        - throttle: 60s
    voltage_l3:
      name: "Voltage Phase 3"
      filters:
        - delta: 1
        - throttle: 60s
    current_l1:
      name: "Current Phase 1"
      filters:
        - throttle: 60s
        - delta: 1
    current_l2:
      name: "Current Phase 2"
      filters:
        - throttle: 60s
        - delta: 1
    current_l3:
      name: "Current Phase 3"
      filters:
        - throttle: 60s
        - delta: 1
    power_delivered_l1:
      name: "Power Consumed Phase 1"
      accuracy_decimals: 3
      filters:
        - throttle: 5s
    power_delivered_l2:
      name: "Power Consumed Phase 2"
      accuracy_decimals: 3
      filters:
        - throttle: 5s
    power_delivered_l3:
      name: "Power Consumed Phase 3"
      accuracy_decimals: 3
      filters:
        - throttle: 5s
    power_returned_l1:
      name: "Power Produced Phase 1"
      accuracy_decimals: 3
      filters:
        - throttle: 5s
    power_returned_l2:
      name: "Power Produced Phase 2"
      accuracy_decimals: 3
      filters:
        - throttle: 5s
    power_returned_l3:
      name: "Power Produced Phase 3"
      accuracy_decimals: 3
      filters:
        - throttle: 5s
  - platform: uptime
    name: "SlimmeLezer Uptime"
  - platform: wifi_signal
    name: "SlimmeLezer Wi-Fi Signal"
    update_interval: 60s

text_sensor:
  - platform: dsmr
    identification:
      name: "DSMR Identification"
    p1_version:
      name: "DSMR Version"
  - platform: wifi_info
    ip_address:
      name: "SlimmeLezer IP Address"
    ssid:
      name: "SlimmeLezer Wi-Fi SSID"
    bssid:
      name: "SlimmeLezer Wi-Fi BSSID"
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true